### PR TITLE
Modify installation of Phalcon DevTools

### PR DESCRIPTION
**Pull request by MilesChou**

### CODE REVIEW

**Comment by fizzka** [comment]
what do you think not to build phalcon-devtools in image, but provide a script, i.e. docker-phalcon-install-devtools which will make this?
(I think that devtools not required by default all of users)

**Comment by MilesChou** [comment]
Oh! Thanks your feedback!

Devtools is not required, I think so, too. But we can provide provide a script, so that all of users can easy to install devtools (like `docker-php-install-*`), if they want. :)

I will using script instead of sample Dockerfile.

**Comment by MilesChou** [comment]
Add script first, but I have no idea about copy to every versions/variants yet.

**Review by fizzka — APPROVED** [review]

**Comment by fizzka** [comment]
it needs to alter builder and other Dockerfiles

**Comment by MilesChou** [comment]
I will fix this issue tonight.

**Comment by fizzka** [comment]
travis:
ERROR: Failed to create usr/libexec/gcc/x86_64-alpine-linux-musl/5.3.0/cc1: No space left on device
ERROR: gcc-5.3.0-r0: No space left on device
fantastic =)

**Comment by MilesChou** [comment]
Rebuild and everything is okay, MAGIC!

**Pull request merged**
