### PR TITLE
bump phalcon-devtools to 3.2.5

### PR DESCRIPTION
**Pull request by fizzka**

### CODE REVIEW

**Comment by MilesChou** [comment]
Thx for your collaborate 😄 

BTW, do you want join collaborator of this project? Because I don't use this Docker image in my work, so that I don't know latest version of Phalcon.

**Comment by fizzka** [comment]
i use phalcon in my works, ready to be a collaborator ;)

**Comment by MilesChou** [comment]
Awesome!! I send invitation mail now, and thanks for you all collaborate. :D

**Comment by fizzka** [comment]
i'm in =)
thanks, good day

2017-09-26 9:00 GMT+03:00 MilesChou <notifications@github.com>:

**Pull request merged**
